'use client';

import { useState, useEffect } from 'react';
import { Plus, Trash2, Download, GripVertical, Search, Loader2, ArrowRight, Globe, MapPin, Upload, FileJson } from 'lucide-react';
import Navbar from '@/components/Navbar';

interface Location {
  id: string;
  code: string;
  city: string;
}

interface AdGroup {
  id: string;
  name: string;
  keywords: string[];
}

interface Campaign {
  name: string;
  locations: Location[];
  adGroups: AdGroup[];
}

export default function CampaignBuilderPage() {
  const [agencyName, setAgencyName] = useState('BA');
  const [campaignId, setCampaignId] = useState('');
  const [productService, setProductService] = useState('');

  const [campaign, setCampaign] = useState<Campaign>({
    name: '',
    locations: [],
    adGroups: [],
  });

  const [keywordPool, setKeywordPool] = useState<string[]>([]);
  const [geoKeywords, setGeoKeywords] = useState<string[]>([]);
  const [nearMeKeywords, setNearMeKeywords] = useState<string[]>([]);
  const [newKeyword, setNewKeyword] = useState('');
  const [draggedKeyword, setDraggedKeyword] = useState<string | null>(null);

  // API Search state
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<any[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [searchError, setSearchError] = useState('');

  // Import state
  const [isDragging, setIsDragging] = useState(false);

  // Auto-generate campaign name
  useEffect(() => {
    const parts = [agencyName, campaignId, productService].filter(p => p.trim());
    if (parts.length > 0) {
      setCampaign(prev => ({ ...prev, name: parts.join(' | ') }));
    } else {
      setCampaign(prev => ({ ...prev, name: '' }));
    }
  }, [agencyName, campaignId, productService]);

  // Import JSON template
  const importJSONTemplate = async (file: File) => {
    try {
      const text = await file.text();
      const data = JSON.parse(text);

      if (!Array.isArray(data) || data.length === 0) {
        alert('Invalid JSON format. Expected an array of campaigns.');
        return;
      }

      // Take the first campaign from the array
      const firstCampaign = data[0];

      // Extract base campaign name parts (format: Agency | ID | Product | Location)
      const nameParts = firstCampaign.campaign_name.split('|').map((p: string) => p.trim());

      // Parse campaign name parts
      const importedAgencyName = nameParts[0] || 'BA';
      const importedCampaignId = nameParts[1] || '';
      const importedProduct = nameParts[2] || '';

      // Extract locations from all campaigns in the file
      const locations: Location[] = data.map((camp: any, index: number) => {
        const nameParts = camp.campaign_name.split('|').map((p: string) => p.trim());
        const code = nameParts[nameParts.length - 1] || ''; // Last part is location code
        return {
          id: `${Date.now()}-${index}`,
          code: code,
          city: camp.location || '',
        };
      });

      // Extract ad groups (use first campaign's structure)
      const adGroups: AdGroup[] = firstCampaign.ad_groups.map((ag: any, index: number) => {
        // Extract ad group name (remove location code prefix like "ATX | ")
        const agName = ag.ad_group.includes('|')
          ? ag.ad_group.split('|')[1].trim()
          : ag.ad_group;

        return {
          id: `${Date.now()}-ag-${index}`,
          name: agName,
          keywords: ag.keywords || [],
        };
      });

      // Update individual fields (campaign name will auto-generate via useEffect)
      setAgencyName(importedAgencyName);
      setCampaignId(importedCampaignId);
      setProductService(importedProduct);

      // Update campaign state
      setCampaign({
        name: '', // Will be auto-generated by useEffect
        locations: locations,
        adGroups: adGroups,
      });

      // Clear keyword pools
      setKeywordPool([]);
      setGeoKeywords([]);
      setNearMeKeywords([]);

      alert(`Template loaded! Campaign with ${locations.length} location(s) and ${adGroups.length} ad group(s)`);
    } catch (error) {
      console.error('Import error:', error);
      alert('Failed to import JSON. Please check the file format.');
    }
  };

  const handleFileUpload = async (files: FileList) => {
    const file = files[0];
    if (!file) return;

    if (file.name.endsWith('.json')) {
      await importJSONTemplate(file);
    } else {
      alert('Please upload a JSON file');
    }
  };

  const handleDragOverUpload = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeaveUpload = () => {
    setIsDragging(false);
  };

  const handleDropUpload = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files) {
      handleFileUpload(e.dataTransfer.files);
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      handleFileUpload(e.target.files);
    }
  };

  // Location management
  const addLocation = () => {
    const newLocation: Location = {
      id: Date.now().toString(),
      code: '',
      city: '',
    };
    setCampaign({
      ...campaign,
      locations: [...campaign.locations, newLocation],
    });
  };

  const updateLocation = (id: string, field: 'code' | 'city', value: string) => {
    setCampaign({
      ...campaign,
      locations: campaign.locations.map(loc =>
        loc.id === id ? { ...loc, [field]: value } : loc
      ),
    });
  };

  const removeLocation = (id: string) => {
    setCampaign({
      ...campaign,
      locations: campaign.locations.filter(loc => loc.id !== id),
    });
  };

  // Ad Group management
  const addAdGroup = () => {
    const newAdGroup: AdGroup = {
      id: Date.now().toString(),
      name: '',
      keywords: [],
    };
    setCampaign({
      ...campaign,
      adGroups: [...campaign.adGroups, newAdGroup],
    });
  };

  const addTriadAdGroups = () => {
    if (campaign.locations.length === 0) {
      alert('Please add at least one location first');
      return;
    }
    if (!productService.trim()) {
      alert('Please enter a Product/Service name first');
      return;
    }

    const timestamp = Date.now();
    const locationCode = campaign.locations[0].code || 'XXX';
    const product = productService.trim();

    const triadGroups: AdGroup[] = [
      {
        id: `${timestamp}-core`,
        name: `${locationCode}_Core_${product}`,
        keywords: [],
      },
      {
        id: `${timestamp}-geo`,
        name: `${locationCode}_Geo_${product}`,
        keywords: [],
      },
      {
        id: `${timestamp}-nearme`,
        name: `${locationCode}_NearMe_${product}`,
        keywords: [],
      },
    ];

    setCampaign({
      ...campaign,
      adGroups: [...campaign.adGroups, ...triadGroups],
    });
  };

  const updateAdGroupName = (id: string, name: string) => {
    setCampaign({
      ...campaign,
      adGroups: campaign.adGroups.map(ag =>
        ag.id === id ? { ...ag, name } : ag
      ),
    });
  };

  const removeAdGroup = (id: string) => {
    setCampaign({
      ...campaign,
      adGroups: campaign.adGroups.filter(ag => ag.id !== id),
    });
  };

  // Keyword pool management
  const addKeywordToPool = () => {
    if (!newKeyword.trim()) return;

    // Split by comma, trim each keyword, filter out empties and duplicates
    const keywords = newKeyword
      .split(',')
      .map(kw => kw.trim())
      .filter(kw => kw && !keywordPool.includes(kw));

    if (keywords.length > 0) {
      setKeywordPool([...keywordPool, ...keywords]);
      setNewKeyword('');
    }
  };

  const removeKeywordFromPool = (keyword: string) => {
    setKeywordPool(keywordPool.filter(k => k !== keyword));
  };

  const removeGeoKeyword = (keyword: string) => {
    setGeoKeywords(geoKeywords.filter(k => k !== keyword));
  };

  const removeNearMeKeyword = (keyword: string) => {
    setNearMeKeywords(nearMeKeywords.filter(k => k !== keyword));
  };

  // API Search function
  const handleSearch = async () => {
    if (!searchQuery.trim()) return;

    setIsSearching(true);
    setSearchError('');
    setSearchResults([]);

    try {
      const response = await fetch('/api/keywords/search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ keyword: searchQuery }),
      });

      if (!response.ok) {
        throw new Error('Failed to fetch keywords');
      }

      const data = await response.json();
      setSearchResults(data.suggestions || []);
    } catch (error) {
      console.error('Search error:', error);
      setSearchError('Failed to fetch keywords. Please try again.');
    } finally {
      setIsSearching(false);
    }
  };

  const addResultToPool = (keyword: string, matchType?: 'exact' | 'phrase' | 'broad') => {
    let formattedKeyword = keyword;

    if (matchType === 'exact') {
      formattedKeyword = `[${keyword}]`;
    } else if (matchType === 'phrase') {
      formattedKeyword = `"${keyword}"`;
    }
    // broad is just the keyword as-is

    if (!keywordPool.includes(formattedKeyword)) {
      setKeywordPool([...keywordPool, formattedKeyword]);
    }
  };

  // Helper function to strip match type modifiers
  const stripMatchType = (keyword: string): string => {
    if (keyword.startsWith('[') && keyword.endsWith(']')) {
      return keyword.slice(1, -1);
    } else if (keyword.startsWith('"') && keyword.endsWith('"')) {
      return keyword.slice(1, -1);
    }
    return keyword;
  };

  // Helper function to strip location names from geo keywords
  const stripLocationFromKeyword = (keyword: string): string => {
    let baseKeyword = stripMatchType(keyword);
    const originalLength = baseKeyword.length;

    // Don't touch "near me" keywords - they're not geo keywords
    if (baseKeyword.toLowerCase().includes('near me')) {
      return ''; // Return empty to skip this keyword
    }

    // Remove current location names
    campaign.locations.forEach(location => {
      const cityName = location.city.split(',')[0].trim().toLowerCase();
      const regex = new RegExp(`\\s+${cityName}\\s*$`, 'i');
      baseKeyword = baseKeyword.replace(regex, '');
    });

    // If no location was stripped, try to strip any single word at the end
    // (this handles cases where location changed from old to new)
    // But NOT common words like "me", "you", "it", etc.
    if (baseKeyword.length === originalLength) {
      const words = baseKeyword.split(/\s+/);
      const lastWord = words[words.length - 1]?.toLowerCase();

      // Don't strip common non-location words
      const nonLocationWords = ['me', 'you', 'us', 'it', 'online', 'today', 'now', 'here'];
      if (!nonLocationWords.includes(lastWord)) {
        // Remove last word (likely an old city name)
        baseKeyword = baseKeyword.replace(/\s+\w+\s*$/, '');
      }
    }

    return baseKeyword.trim();
  };

  // Helper function to get match type badge
  const getMatchTypeBadge = (keyword: string) => {
    if (keyword.startsWith('[') && keyword.endsWith(']')) {
      return { type: 'exact', label: 'E', color: 'bg-purple-100 text-purple-800 border-purple-300' };
    } else if (keyword.startsWith('"') && keyword.endsWith('"')) {
      return { type: 'phrase', label: 'P', color: 'bg-green-100 text-green-800 border-green-300' };
    }
    return { type: 'broad', label: 'B', color: 'bg-orange-100 text-orange-800 border-orange-300' };
  };

  // Generate Geo Keywords (Exact + Phrase only)
  const generateGeoKeywords = () => {
    if (campaign.locations.length === 0) {
      alert('Please add at least one location first');
      return;
    }
    if (keywordPool.length === 0) {
      alert('Please add keywords to the pool first');
      return;
    }

    const geoKws: string[] = [];
    keywordPool.forEach(keyword => {
      campaign.locations.forEach(location => {
        // Extract just the city name (e.g., "Austin" from "Austin, TX")
        const cityName = location.city.split(',')[0].trim().toLowerCase();
        // Strip existing match type and get base keyword
        const baseKeyword = stripMatchType(keyword);
        const geoTerm = `${baseKeyword} ${cityName}`;

        // Add Exact and Phrase versions (no Broad)
        geoKws.push(`[${geoTerm}]`); // Exact
        geoKws.push(`"${geoTerm}"`); // Phrase
      });
    });

    setGeoKeywords(geoKws);
  };

  // Refresh Geo Keywords with updated location information
  const refreshGeoKeywords = () => {
    if (campaign.locations.length === 0) {
      alert('Please add at least one location first');
      return;
    }

    // Extract unique base keywords from existing geo keywords
    const baseKeywords = new Set<string>();
    geoKeywords.forEach(keyword => {
      const base = stripLocationFromKeyword(keyword);
      if (base) {
        baseKeywords.add(base);
      }
    });

    // Also extract base keywords from ad groups
    // Look for keywords in Geo ad groups or keywords that have location suffixes
    campaign.adGroups.forEach(adGroup => {
      // Check if this is a geo ad group
      const isGeoGroup = adGroup.name.toLowerCase().includes('geo') || adGroup.name.toLowerCase().includes('city');

      adGroup.keywords.forEach(keyword => {
        const stripped = stripMatchType(keyword);
        const base = stripLocationFromKeyword(keyword);

        // Add if:
        // 1. It's in a geo ad group, OR
        // 2. A location was actually stripped (base is shorter than original)
        if (base && (isGeoGroup || base.length < stripped.length)) {
          baseKeywords.add(base);
        }
      });
    });

    if (baseKeywords.size === 0) {
      alert('No geo keywords found. Either:\n1. Generate geo keywords using the Geo button\n2. Import a JSON with geo keywords\n3. Add keywords with location names to ad groups');
      return;
    }

    // Create a mapping of old keywords to new keywords
    const keywordMapping = new Map<string, string>();

    // Generate new geo keywords
    const geoKws: string[] = [];
    baseKeywords.forEach(baseKeyword => {
      campaign.locations.forEach(location => {
        const cityName = location.city.split(',')[0].trim().toLowerCase();
        const geoTerm = `${baseKeyword} ${cityName}`;

        const exactMatch = `[${geoTerm}]`;
        const phraseMatch = `"${geoTerm}"`;

        // Add to new geo keywords list
        geoKws.push(exactMatch);
        geoKws.push(phraseMatch);

        // Map old keywords to new ones for replacement in ad groups
        // Old keywords might have different locations, so we map base keyword with match type
        keywordMapping.set(`[${baseKeyword}]`, exactMatch);
        keywordMapping.set(`"${baseKeyword}"`, phraseMatch);
      });
    });

    // Update geo keywords list
    setGeoKeywords(geoKws);

    // Update keywords in ad groups (ONLY in Geo ad groups)
    let updatedCount = 0;
    const updatedAdGroups = campaign.adGroups.map(adGroup => {
      // Only update keywords in Geo or City ad groups
      const isGeoGroup = adGroup.name.toLowerCase().includes('geo') || adGroup.name.toLowerCase().includes('city');

      if (!isGeoGroup) {
        // Skip non-geo ad groups - don't touch Core or NearMe keywords
        return adGroup;
      }

      const updatedKeywords = adGroup.keywords.map(keyword => {
        const base = stripLocationFromKeyword(keyword);
        const matchType = keyword.startsWith('[') ? '[' : keyword.startsWith('"') ? '"' : '';

        // Check if this keyword has a location that needs updating
        if (base && base !== stripMatchType(keyword)) {
          // This is a geo keyword, regenerate it
          const cityName = campaign.locations[0]?.city.split(',')[0].trim().toLowerCase();
          if (cityName) {
            updatedCount++;
            if (matchType === '[') {
              return `[${base} ${cityName}]`;
            } else if (matchType === '"') {
              return `"${base} ${cityName}"`;
            }
          }
        }
        return keyword;
      });

      return {
        ...adGroup,
        keywords: updatedKeywords,
      };
    });

    setCampaign({
      ...campaign,
      adGroups: updatedAdGroups,
    });

    alert(`Refreshed ${geoKws.length} geo keywords and updated ${updatedCount} keywords in ad groups`);
  };

  // Generate Near Me Keywords (Phrase only)
  const generateNearMeKeywords = () => {
    if (keywordPool.length === 0) {
      alert('Please add keywords to the pool first');
      return;
    }

    const nearMeKws: string[] = keywordPool.map(keyword => {
      // Strip existing match type and get base keyword
      const baseKeyword = stripMatchType(keyword);
      // Add only Phrase match
      return `"${baseKeyword} near me"`;
    });

    setNearMeKeywords(nearMeKws);
  };

  // Drag and drop handlers
  const handleDragStart = (keyword: string) => {
    setDraggedKeyword(keyword);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const handleDrop = (adGroupId: string) => {
    if (!draggedKeyword) return;

    // Check if keyword already exists in this ad group
    const adGroup = campaign.adGroups.find(ag => ag.id === adGroupId);
    if (adGroup?.keywords.includes(draggedKeyword)) {
      setDraggedKeyword(null);
      return;
    }

    setCampaign({
      ...campaign,
      adGroups: campaign.adGroups.map(ag =>
        ag.id === adGroupId
          ? { ...ag, keywords: [...ag.keywords, draggedKeyword] }
          : ag
      ),
    });

    // Remove from pool if it exists there
    if (keywordPool.includes(draggedKeyword)) {
      setKeywordPool(keywordPool.filter(k => k !== draggedKeyword));
    }
    // Remove from geo keywords if it exists there
    if (geoKeywords.includes(draggedKeyword)) {
      setGeoKeywords(geoKeywords.filter(k => k !== draggedKeyword));
    }
    // Remove from near me keywords if it exists there
    if (nearMeKeywords.includes(draggedKeyword)) {
      setNearMeKeywords(nearMeKeywords.filter(k => k !== draggedKeyword));
    }

    setDraggedKeyword(null);
  };

  const removeKeywordFromAdGroup = (adGroupId: string, keyword: string) => {
    setCampaign({
      ...campaign,
      adGroups: campaign.adGroups.map(ag =>
        ag.id === adGroupId
          ? { ...ag, keywords: ag.keywords.filter(k => k !== keyword) }
          : ag
      ),
    });
    // Add back to pool
    setKeywordPool([...keywordPool, keyword]);
  };

  // Export functions
  const exportKeywordsJSON = () => {
    const exports = campaign.locations.map(location => ({
      campaign_name: `${campaign.name} | ${location.code}`,
      location: location.city,
      ad_groups: campaign.adGroups.map(ag => {
        // Check if ad group name already starts with location code
        const startsWithLocation = ag.name.toUpperCase().startsWith(location.code.toUpperCase());
        const adGroupName = startsWithLocation
          ? ag.name // Already has location code
          : `${location.code}_${ag.name}`; // Add location code

        return {
          ad_group: adGroupName,
          keywords: ag.keywords,
        };
      }),
    }));

    // Generate filename with location codes
    const locationCodes = campaign.locations.map(loc => loc.code).filter(code => code).join('_');
    const baseName = campaign.name.replace(/\s+/g, '_').replace(/\|/g, '');
    const fileName = locationCodes
      ? `${baseName}_${locationCodes}_keywords.json`
      : `${baseName}_keywords.json`;

    const blob = new Blob([JSON.stringify(exports, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportAdCopyJSON = () => {
    const exports = campaign.locations.map(location => ({
      campaign: `${campaign.name} | ${location.code}`,
      responsive_search_ad: {
        final_url: '',
        path_1: '',
        path_2: '',
        headlines: [],
        descriptions: [],
      },
    }));

    const blob = new Blob([JSON.stringify(exports, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${campaign.name.replace(/\s+/g, '_')}_ads.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <Navbar />
      <div className="ml-64 min-h-screen bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">Campaign Structure Builder</h1>
          <p className="mt-2 text-gray-600">
            Build your campaign structure and generate JSON files for Keywords and Ads
          </p>
        </div>

        {/* Import Template Section */}
        <div className="bg-gradient-to-r from-blue-50 to-purple-50 border-2 border-dashed border-blue-300 rounded-lg p-6 mb-6">
          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
              <div className="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center">
                <Upload className="h-6 w-6 text-white" />
              </div>
            </div>
            <div className="flex-1">
              <h3 className="text-lg font-semibold text-gray-900 mb-2">
                Start from a Template
              </h3>
              <p className="text-sm text-gray-600 mb-4">
                Upload a previously exported campaign JSON to pre-fill locations, ad groups, and keywords. Perfect for creating similar campaigns or expanding to new locations.
              </p>
              <div
                className={`border-2 border-dashed rounded-lg p-6 text-center transition-colors ${
                  isDragging
                    ? 'border-blue-500 bg-blue-50'
                    : 'border-gray-300 bg-white hover:border-blue-400'
                }`}
                onDrop={handleDropUpload}
                onDragOver={handleDragOverUpload}
                onDragLeave={handleDragLeaveUpload}
              >
                <FileJson className="mx-auto h-8 w-8 text-blue-600 mb-2" />
                <label htmlFor="json-upload" className="cursor-pointer">
                  <span className="text-blue-600 hover:text-blue-500 font-medium">
                    Click to upload JSON template
                  </span>
                  <span className="text-gray-600"> or drag and drop</span>
                </label>
                <input
                  id="json-upload"
                  type="file"
                  accept=".json"
                  className="hidden"
                  onChange={handleFileSelect}
                />
                <p className="text-xs text-gray-500 mt-2">
                  Upload a keywords JSON file exported from this tool
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Campaign Setup */}
        <div className="bg-white rounded-lg shadow p-6 mb-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Campaign Setup</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Agency Name
              </label>
              <input
                type="text"
                value={agencyName}
                onChange={(e) => setAgencyName(e.target.value)}
                placeholder="e.g., BA"
                maxLength={10}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-gray-900"
              />
              <p className="text-xs text-gray-500 mt-1">
                BA = Bullseye Agency
              </p>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Campaign ID
              </label>
              <input
                type="text"
                value={campaignId}
                onChange={(e) => setCampaignId(e.target.value)}
                placeholder="e.g., 001"
                maxLength={10}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-gray-900"
              />
              <p className="text-xs text-gray-500 mt-1">
                3-digit campaign number
              </p>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Product/Service
              </label>
              <input
                type="text"
                value={productService}
                onChange={(e) => setProductService(e.target.value)}
                placeholder="e.g., Mechanical Bull"
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-gray-900"
              />
              <p className="text-xs text-gray-500 mt-1">
                Product or service name
              </p>
            </div>
          </div>
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Generated Campaign Name
            </label>
            <div className="text-lg font-semibold text-gray-900">
              {campaign.name || <span className="text-gray-400">Enter details above to generate campaign name</span>}
            </div>
            <p className="text-xs text-gray-500 mt-1">
              Format: Agency Name | Campaign ID | Product/Service
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* First Column: Locations & Ad Groups */}
          <div className="space-y-6">
            {/* Locations */}
            <div className="bg-white rounded-lg shadow p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-semibold text-gray-900">Locations</h2>
                <button
                  onClick={addLocation}
                  className="flex items-center gap-2 px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm"
                >
                  <Plus className="h-4 w-4" />
                  Add Location
                </button>
              </div>
              <div className="space-y-3">
                {campaign.locations.map((location) => (
                  <div key={location.id} className="space-y-2">
                    <div className="flex gap-2">
                      <input
                        type="text"
                        value={location.code}
                        onChange={(e) => updateLocation(location.id, 'code', e.target.value.toUpperCase())}
                        placeholder="ATX"
                        maxLength={3}
                        className="w-20 px-3 py-2 text-sm text-gray-900 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent uppercase"
                      />
                      <input
                        type="text"
                        value={location.city}
                        onChange={(e) => updateLocation(location.id, 'city', e.target.value)}
                        placeholder="Austin, TX"
                        className="flex-1 px-3 py-2 text-sm text-gray-900 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      />
                      <button
                        onClick={() => removeLocation(location.id)}
                        className="p-2 text-red-600 hover:bg-red-50 rounded-lg"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </div>
                    {campaign.name && location.code && (
                      <div className="ml-1 px-2 py-1 bg-blue-50 border border-blue-200 rounded text-xs">
                        <span className="text-gray-600">Exported as: </span>
                        <span className="font-semibold text-blue-900">{campaign.name} | {location.code}</span>
                      </div>
                    )}
                  </div>
                ))}
                {campaign.locations.length === 0 && (
                  <p className="text-sm text-gray-500 text-center py-4">
                    No locations added yet
                  </p>
                )}
              </div>
            </div>

            {/* Ad Groups */}
            <div className="bg-white rounded-lg shadow p-6">
              <div className="mb-4">
                <div className="flex items-center justify-between mb-2">
                  <h2 className="text-lg font-semibold text-gray-900">Ad Groups</h2>
                  <div className="flex gap-2">
                    <button
                      onClick={refreshGeoKeywords}
                      disabled={campaign.locations.length === 0}
                      className="flex items-center gap-2 px-3 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors text-sm"
                      title="Refresh geo keywords with updated location information"
                    >
                      <ArrowRight className="h-4 w-4" />
                      Refresh Geo
                    </button>
                    <button
                      onClick={addTriadAdGroups}
                      disabled={!productService.trim() || campaign.locations.length === 0}
                      className="flex items-center gap-2 px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors text-sm"
                      title="Create Core, Geo, and Near Me ad groups"
                    >
                      <Plus className="h-4 w-4" />
                      Add Triad
                    </button>
                    <button
                      onClick={addAdGroup}
                      className="flex items-center gap-2 px-3 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors text-sm"
                    >
                      <Plus className="h-4 w-4" />
                      Add Ad Group
                    </button>
                  </div>
                </div>
                <p className="text-xs text-gray-500 italic">
                  Core → Broad + Exact • Geo → Exact + Phrase • Near Me → Phrase only
                </p>
              </div>
              <div className="space-y-4">
                {campaign.adGroups.map((adGroup) => (
                  <div
                    key={adGroup.id}
                    onDragOver={handleDragOver}
                    onDrop={() => handleDrop(adGroup.id)}
                    className="border-2 border-dashed border-gray-300 rounded-lg p-4 hover:border-purple-400 transition-colors"
                  >
                    <div className="flex items-center gap-2 mb-3">
                      <input
                        type="text"
                        value={adGroup.name}
                        onChange={(e) => updateAdGroupName(adGroup.id, e.target.value)}
                        placeholder="Ad Group Name (e.g., Core, City, Near Me)"
                        className="flex-1 px-3 py-2 text-sm font-medium text-gray-900 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                      />
                      <button
                        onClick={() => removeAdGroup(adGroup.id)}
                        className="p-2 text-red-600 hover:bg-red-50 rounded-lg"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </div>
                    <div className="space-y-1">
                      {adGroup.keywords.length === 0 ? (
                        <p className="text-xs text-gray-400 text-center py-4">
                          Drag keywords here
                        </p>
                      ) : (
                        adGroup.keywords.map((keyword, idx) => {
                          const badge = getMatchTypeBadge(keyword);
                          return (
                            <div
                              key={idx}
                              className="flex items-center gap-2 px-2 py-1 bg-purple-50 border border-purple-200 rounded text-sm"
                            >
                              <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-xs font-bold border ${badge.color}`}>
                                {badge.label}
                              </span>
                              <span className="flex-1 text-gray-900 font-mono text-xs">{keyword}</span>
                              <button
                                onClick={() => removeKeywordFromAdGroup(adGroup.id, keyword)}
                                className="p-1 text-red-600 hover:bg-red-50 rounded"
                              >
                                <Trash2 className="h-3 w-3" />
                              </button>
                            </div>
                          );
                        })
                      )}
                    </div>
                    <p className="text-xs text-gray-500 mt-2">
                      {adGroup.keywords.length} keyword{adGroup.keywords.length !== 1 ? 's' : ''}
                    </p>
                  </div>
                ))}
                {campaign.adGroups.length === 0 && (
                  <p className="text-sm text-gray-500 text-center py-8">
                    No ad groups added yet
                  </p>
                )}
              </div>
            </div>
          </div>

          {/* Second Column: Find Keywords, Keyword Pool, Geo, Near Me */}
          <div className="space-y-6">
            {/* Find Keywords */}
            <div className="bg-white rounded-lg shadow p-6">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Find Keywords</h2>
              <div className="flex gap-2 mb-4">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
                    placeholder="Search for keywords..."
                    disabled={isSearching}
                    className="w-full pl-10 pr-4 py-2 text-sm text-gray-900 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-100"
                  />
                </div>
                <button
                  onClick={handleSearch}
                  disabled={isSearching || !searchQuery.trim()}
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm flex items-center gap-2 disabled:bg-gray-300 disabled:cursor-not-allowed"
                >
                  {isSearching ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <Search className="h-4 w-4" />
                  )}
                  {isSearching ? 'Searching...' : 'Search'}
                </button>
              </div>

              {/* Search Results */}
              <div className="bg-gray-50 border border-gray-200 rounded-lg max-h-96 overflow-y-auto">
                {searchError && (
                  <div className="p-4 text-sm text-red-600 text-center">
                    {searchError}
                  </div>
                )}

                {!isSearching && !searchError && searchResults.length === 0 && (
                  <div className="p-4 text-sm text-gray-500 text-center">
                    Enter a seed keyword to find related keywords via API
                  </div>
                )}

                {searchResults.length > 0 && (
                  <div className="divide-y divide-gray-200">
                    {searchResults.map((result, index) => (
                      <div
                        key={index}
                        draggable
                        onDragStart={() => handleDragStart(result.keyword)}
                        className="p-3 hover:bg-gray-100 transition-colors cursor-move"
                      >
                        <div className="flex items-start justify-between gap-3">
                          <div className="flex items-start gap-2 flex-1">
                            <GripVertical className="h-4 w-4 text-gray-400 mt-1 flex-shrink-0" />
                            <div className="flex-1 min-w-0">
                              <p className="text-sm font-medium text-gray-900 font-mono break-words">
                                {result.keyword}
                              </p>
                              <div className="flex flex-wrap gap-3 mt-1 text-xs text-gray-600">
                                <span>Vol: {result.search_volume?.toLocaleString() || 'N/A'}</span>
                                <span>CPC: ${result.cpc?.toFixed(2) || 'N/A'}</span>
                                <span className={`font-medium ${
                                  result.competition === 'HIGH' ? 'text-red-600' :
                                  result.competition === 'MEDIUM' ? 'text-yellow-600' :
                                  'text-green-600'
                                }`}>
                                  {result.competition || result.competition_index ?
                                    `Comp: ${result.competition || Math.round(result.competition_index * 100) + '%'}` :
                                    'Comp: N/A'}
                                </span>
                              </div>
                            </div>
                          </div>
                          <div className="flex gap-1 flex-shrink-0">
                            <button
                              onClick={() => addResultToPool(result.keyword, 'exact')}
                              disabled={keywordPool.includes(`[${result.keyword}]`)}
                              className="px-2 py-1 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors text-xs font-medium"
                              title="Add as Exact Match [keyword]"
                            >
                              +Exact
                            </button>
                            <button
                              onClick={() => addResultToPool(result.keyword, 'phrase')}
                              disabled={keywordPool.includes(`"${result.keyword}"`)}
                              className="px-2 py-1 bg-purple-600 text-white rounded hover:bg-purple-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors text-xs font-medium"
                              title="Add as Phrase Match &quot;keyword&quot;"
                            >
                              +Phrase
                            </button>
                            <button
                              onClick={() => addResultToPool(result.keyword, 'broad')}
                              disabled={keywordPool.includes(result.keyword)}
                              className="px-2 py-1 bg-green-600 text-white rounded hover:bg-green-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors text-xs font-medium"
                              title="Add as Broad Match (keyword)"
                            >
                              +Broad
                            </button>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Keyword Pool */}
            <div className="bg-white rounded-lg shadow p-6">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                  <h2 className="text-lg font-semibold text-gray-900">Keyword Pool</h2>
                  <div className="flex items-center gap-2 text-xs">
                    <span className="inline-flex items-center px-1.5 py-0.5 rounded border font-bold bg-purple-100 text-purple-800 border-purple-300">E</span>
                    <span className="inline-flex items-center px-1.5 py-0.5 rounded border font-bold bg-green-100 text-green-800 border-green-300">P</span>
                    <span className="inline-flex items-center px-1.5 py-0.5 rounded border font-bold bg-orange-100 text-orange-800 border-orange-300">B</span>
                  </div>
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={generateGeoKeywords}
                    disabled={keywordPool.length === 0 || campaign.locations.length === 0}
                    className="flex items-center gap-1 px-3 py-1 bg-orange-600 text-white rounded-lg hover:bg-orange-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors text-sm"
                    title="Generate Exact + Phrase geo keywords"
                  >
                    <Globe className="h-4 w-4" />
                    Geo
                  </button>
                  <button
                    onClick={generateNearMeKeywords}
                    disabled={keywordPool.length === 0}
                    className="flex items-center gap-1 px-3 py-1 bg-teal-600 text-white rounded-lg hover:bg-teal-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors text-sm"
                    title="Generate Phrase 'near me' keywords"
                  >
                    <MapPin className="h-4 w-4" />
                    Near Me
                  </button>
                </div>
              </div>
              <div className="flex gap-2 mb-4">
                <input
                  type="text"
                  value={newKeyword}
                  onChange={(e) => setNewKeyword(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && addKeywordToPool()}
                  placeholder="Enter keywords (comma-separated) and press Enter"
                  className="flex-1 px-3 py-2 text-sm text-gray-900 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
                <button
                  onClick={addKeywordToPool}
                  className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors text-sm"
                >
                  <Plus className="h-4 w-4" />
                </button>
              </div>
              <div className="space-y-2 max-h-96 overflow-y-auto">
                {keywordPool.map((keyword, index) => {
                  const badge = getMatchTypeBadge(keyword);
                  return (
                    <div
                      key={index}
                      draggable
                      onDragStart={() => handleDragStart(keyword)}
                      className="flex items-center gap-2 px-3 py-2 bg-blue-50 border border-blue-200 rounded-lg cursor-move hover:bg-blue-100 transition-colors"
                    >
                      <GripVertical className="h-4 w-4 text-gray-400" />
                      <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-xs font-bold border ${badge.color}`}>
                        {badge.label}
                      </span>
                      <span className="flex-1 text-sm text-gray-900 font-mono">{keyword}</span>
                      <button
                        onClick={() => removeKeywordFromPool(keyword)}
                        className="p-1 text-red-600 hover:bg-red-50 rounded"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                    </div>
                  );
                })}
                {keywordPool.length === 0 && (
                  <p className="text-sm text-gray-500 text-center py-8">
                    No keywords in pool. Add keywords manually or use API (coming soon)
                  </p>
                )}
              </div>
            </div>

            {/* Geo Keywords */}
            <div className="bg-white rounded-lg shadow p-6">
              <div className="flex items-center gap-2 mb-4">
                <Globe className="h-5 w-5 text-orange-600" />
                <h2 className="text-lg font-semibold text-gray-900">Geo Keywords</h2>
                <span className="text-sm text-gray-500">({geoKeywords.length})</span>
              </div>
              <div className="space-y-2 max-h-96 overflow-y-auto">
                {geoKeywords.map((keyword, index) => {
                  const badge = getMatchTypeBadge(keyword);
                  return (
                    <div
                      key={index}
                      draggable
                      onDragStart={() => handleDragStart(keyword)}
                      className="flex items-center gap-2 px-3 py-2 bg-orange-50 border border-orange-200 rounded-lg cursor-move hover:bg-orange-100 transition-colors"
                    >
                      <GripVertical className="h-4 w-4 text-gray-400" />
                      <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-xs font-bold border ${badge.color}`}>
                        {badge.label}
                      </span>
                      <span className="flex-1 text-sm text-gray-900 font-mono">{keyword}</span>
                      <button
                        onClick={() => removeGeoKeyword(keyword)}
                        className="p-1 text-red-600 hover:bg-red-50 rounded"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                    </div>
                  );
                })}
                {geoKeywords.length === 0 && (
                  <p className="text-sm text-gray-500 text-center py-8">
                    Click "Geo" button above to generate location-based keywords
                  </p>
                )}
              </div>
            </div>

            {/* Near Me Keywords */}
            <div className="bg-white rounded-lg shadow p-6">
              <div className="flex items-center gap-2 mb-4">
                <MapPin className="h-5 w-5 text-teal-600" />
                <h2 className="text-lg font-semibold text-gray-900">Near Me Keywords</h2>
                <span className="text-sm text-gray-500">({nearMeKeywords.length})</span>
              </div>
              <div className="space-y-2 max-h-96 overflow-y-auto">
                {nearMeKeywords.map((keyword, index) => {
                  const badge = getMatchTypeBadge(keyword);
                  return (
                    <div
                      key={index}
                      draggable
                      onDragStart={() => handleDragStart(keyword)}
                      className="flex items-center gap-2 px-3 py-2 bg-teal-50 border border-teal-200 rounded-lg cursor-move hover:bg-teal-100 transition-colors"
                    >
                      <GripVertical className="h-4 w-4 text-gray-400" />
                      <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-xs font-bold border ${badge.color}`}>
                        {badge.label}
                      </span>
                      <span className="flex-1 text-sm text-gray-900 font-mono">{keyword}</span>
                      <button
                        onClick={() => removeNearMeKeyword(keyword)}
                        className="p-1 text-red-600 hover:bg-red-50 rounded"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                    </div>
                  );
                })}
                {nearMeKeywords.length === 0 && (
                  <p className="text-sm text-gray-500 text-center py-8">
                    Click "Near Me" button above to generate proximity keywords
                  </p>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Export Section */}
        <div className="mt-6 bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Export Campaign</h2>
          <div className="flex gap-4">
            <button
              onClick={exportKeywordsJSON}
              disabled={!campaign.name || campaign.locations.length === 0 || campaign.adGroups.length === 0}
              className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
            >
              <Download className="h-5 w-5" />
              Export Keywords JSON
            </button>
            <button
              onClick={exportAdCopyJSON}
              disabled={!campaign.name || campaign.locations.length === 0}
              className="flex items-center gap-2 px-6 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
            >
              <Download className="h-5 w-5" />
              Export Ad Copy Template
            </button>
          </div>
          <div className="mt-4 bg-blue-50 border border-blue-200 rounded-lg p-4">
            <p className="text-sm text-blue-900">
              <strong>💡 Tip:</strong> Keywords JSON can be re-imported as a template. Export → Edit JSON file → Re-import to create similar campaigns faster.
            </p>
          </div>
        </div>
        </div>
      </div>
    </>
  );
}
